### ISSUE TITLE
[Crash]: game crashes during fight with Wither boss

### ISSUE THREAD

**Issue by vlad8599** [Fuzss/forgeconfigapiport#51]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.4

### Mod Version (Required)

20.0.4

### Notes (Required)

1. Summon the Wither and wait until its ready to destroy everything around.
2. Start hitting Wither with your best weapon(I was using a sword).
3. At some moment, after trying to hit boss one more time, your game will crash.

Log saying that problem is inside Forge API for Fabric(this mod). Can you fix it please?

### Crash Report (Required)

https://gist.github.com/vlad8599/6b843bdec96607d30cac8cde57114f09

### latest.log (Optional)

https://gist.github.com/vlad8599/5bdcbbe9b6d5eeaa2c1adb22678ea0ca

**Comment by Fuzss** [comment]
The game already crashed before FCAP ran into an issue due to the unexpected shutdown:
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at net.minecraft.client.sound.SoundSystem.tick(SoundSystem.java:285) ~[client-intermediary.jar:?]
	at net.minecraft.client.sound.SoundSystem.tick(SoundSystem.java:247) ~[client-intermediary.jar:?]
	at net.minecraft.client.sound.SoundManager.tick(SoundManager.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
`
``
